name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: ['25', '26', '27', '28', '29']
    runs-on: ubuntu-24.04
    container:
      image: public.ecr.aws/docker/library/erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v6
    - run: REBAR=rebar make
    - run: TEST=true make
    - run: make eunit
    - run: make xref
    - run: make dialyzer
    - run: make test
    - name: Send to Coveralls
      if: matrix.otp == 28
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        COVERALLS=true TEST=true rebar3 as test coveralls send
        curl -v -k https://coveralls.io/webhook \
             --header "Content-Type: application/json" \
             --data '{"repo_name":"$GITHUB_REPOSITORY",
                      "repo_token":"$GITHUB_TOKEN",
                      "payload":{"build_num":$GITHUB_RUN_ID,
                                 "status":"done"}}'
